// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Rajesh D'Monte
#include "console/ConsoleServer.h"

#include "console/Password.h"
#include "cvar/Console.h"
#include "platform/Log.h"

// Embedded web frontend (generated by vox_embed_resource). Referenced so the
// embedded objects link, and served by the HTTP handler below.
extern "C" const unsigned char web_index_html_data[];
extern "C" const unsigned long web_index_html_size;
extern "C" const unsigned char web_console_js_data[];
extern "C" const unsigned long web_console_js_size;
extern "C" const unsigned char web_console_css_data[];
extern "C" const unsigned long web_console_css_size;

#if defined(VOX_HAVE_CONSOLE_SERVER)

#include <atomic>
#include <chrono>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <future>
#include <iterator>
#include <set>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include <winsock2.h>
#include <ws2tcpip.h>

#include <civetweb.h>
#include <nlohmann/json.hpp>
#include <sodium.h>

#if defined(VOX_HAVE_TLS)
#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#endif

using json = nlohmann::json;
using clock_t_ = std::chrono::steady_clock;

namespace vox::console {
namespace {

const char* TypeName(CVarType t) {
    switch (t) {
    case CVarType::Int: return "int";
    case CVarType::Float: return "float";
    case CVarType::Bool: return "bool";
    case CVarType::Enum: return "enum";
    case CVarType::Vec3: return "vec3";
    case CVarType::Color: return "color";
    case CVarType::String: return "string";
    }
    return "string";
}

json CvarToJson(const CVar& cv) {
    return json{{"name", cv.name}, {"value", cv.value}, {"default", cv.default_value},
                {"description", cv.description}, {"type", TypeName(cv.type)}, {"flags", cv.flags},
                {"enum_values", cv.enum_values}, {"range_min", cv.range_min}, {"range_max", cv.range_max},
                {"range_step", cv.range_step}, {"live_tunable", cv.live_tunable}};
}

std::string RandomToken() {
    unsigned char buf[32];
    randombytes_buf(buf, sizeof(buf));
    static const char* hx = "0123456789abcdef";
    std::string s;
    s.reserve(64);
    for (unsigned char b : buf) {
        s.push_back(hx[b >> 4]);
        s.push_back(hx[b & 15]);
    }
    return s;
}

std::string CookieValue(const char* cookie, const std::string& name) {
    if (!cookie) return {};
    std::string c(cookie);
    std::string key = name + "=";
    auto p = c.find(key);
    if (p == std::string::npos) return {};
    p += key.size();
    auto e = c.find(';', p);
    return c.substr(p, e == std::string::npos ? std::string::npos : e - p);
}

std::string QueryParam(const char* qs, const std::string& name) {
    if (!qs) return {};
    char buf[256];
    int n = mg_get_var(qs, std::strlen(qs), name.c_str(), buf, sizeof(buf));
    return n > 0 ? std::string(buf, n) : std::string{};
}

#if defined(VOX_HAVE_TLS)
std::string Sha256Fingerprint(X509* cert) {
    unsigned char md[EVP_MAX_MD_SIZE];
    unsigned int n = 0;
    X509_digest(cert, EVP_sha256(), md, &n);
    static const char* hx = "0123456789ABCDEF";
    std::string s;
    for (unsigned int i = 0; i < n; ++i) {
        if (i) s.push_back(':');
        s.push_back(hx[md[i] >> 4]);
        s.push_back(hx[md[i] & 15]);
    }
    return s;
}

// Generate a self-signed localhost cert + key into `pemPath`. Returns the
// SHA-256 fingerprint, or empty on failure.
std::string GenerateSelfSignedCert(const std::string& pemPath) {
    EVP_PKEY* pkey = EVP_RSA_gen(2048);
    if (!pkey) return {};
    X509* x = X509_new();
    ASN1_INTEGER_set(X509_get_serialNumber(x), 1);
    X509_gmtime_adj(X509_getm_notBefore(x), 0);
    X509_gmtime_adj(X509_getm_notAfter(x), 60LL * 60 * 24 * 825);
    X509_set_pubkey(x, pkey);
    X509_NAME* name = X509_get_subject_name(x);
    X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const unsigned char*>("localhost"), -1, -1, 0);
    X509_set_issuer_name(x, name);
    // SAN: localhost + 127.0.0.1
    if (X509_EXTENSION* ext = X509V3_EXT_conf_nid(nullptr, nullptr, NID_subject_alt_name,
                                                  const_cast<char*>("DNS:localhost,IP:127.0.0.1"))) {
        X509_add_ext(x, ext, -1);
        X509_EXTENSION_free(ext);
    }
    X509_sign(x, pkey, EVP_sha256());

    // Serialize via a memory BIO (NOT a FILE* -- passing the app's FILE* to
    // OpenSSL on Windows requires applink.c / a shared CRT and otherwise
    // crashes with "no OPENSSL_Applink"). Write the bytes ourselves.
    std::string fp;
    BIO* bio = BIO_new(BIO_s_mem());
    if (bio) {
        PEM_write_bio_X509(bio, x);
        PEM_write_bio_PrivateKey(bio, pkey, nullptr, nullptr, 0, nullptr, nullptr);
        char* data = nullptr;
        long len = BIO_get_mem_data(bio, &data);
        std::ofstream out(pemPath, std::ios::binary | std::ios::trunc);
        if (out && data && len > 0) out.write(data, len);
        BIO_free(bio);
        fp = Sha256Fingerprint(x);
    }
    X509_free(x);
    EVP_PKEY_free(pkey);
    return fp;
}
#endif  // VOX_HAVE_TLS

}  // namespace

// ---- Impl -----------------------------------------------------------------
struct ConsoleServer::Impl {
    mg_context* ctx = nullptr;

    std::mutex ws_mutex;
    std::unordered_map<const mg_connection*, std::set<std::string>> ws_clients;  // conn -> subscribed topics

    struct Session {
        clock_t_::time_point created;
        clock_t_::time_point last_active;
        std::string source;
    };
    std::mutex sess_mutex;
    std::unordered_map<std::string, Session> sessions;

    struct Rate {
        int fails = 0;
        clock_t_::time_point lockout_until;
    };
    std::mutex rl_mutex;
    std::unordered_map<std::string, Rate> rate;
    std::atomic<int> total_fails{0};
    std::atomic<bool> force_unbind{false};

    std::string cert_path;
    std::string fingerprint;
    int ttl_seconds = 3600;
    bool tls = false;
    std::uint16_t port = 27960;

    // TCP line-protocol automation listener.
    SOCKET line_sock = INVALID_SOCKET;
    std::thread line_thread;
    std::vector<std::thread> line_workers;
    std::atomic<bool> line_run{false};
    bool wsa_started = false;

    bool OriginAllowed(const char* origin) const {
        if (!origin) return true;  // non-browser (raw) clients send no Origin
        const char* scheme = tls ? "https" : "http";
        std::string a = fmt::format("{}://localhost:{}", scheme, port);
        std::string b = fmt::format("{}://127.0.0.1:{}", scheme, port);
        return origin == a || origin == b;
    }
    bool SessionValid(const std::string& token) {
        if (token.empty()) return false;
        std::lock_guard<std::mutex> lk(sess_mutex);
        auto it = sessions.find(token);
        if (it == sessions.end()) return false;
        auto now = clock_t_::now();
        if (std::chrono::duration_cast<std::chrono::seconds>(now - it->second.last_active).count() > ttl_seconds) {
            sessions.erase(it);
            return false;
        }
        it->second.last_active = now;
        return true;
    }
};

// ---- HTTP -----------------------------------------------------------------
static void SendBytes(mg_connection* c, const char* ctype, const unsigned char* data, unsigned long size) {
    mg_printf(c, "HTTP/1.1 200 OK\r\nContent-Type: %s\r\nContent-Length: %lu\r\nCache-Control: no-store\r\n\r\n", ctype, size);
    mg_write(c, data, size);
}

int ConsoleServer::HttpHandler(mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    const mg_request_info* ri = mg_get_request_info(conn);
    std::string uri = ri->local_uri ? ri->local_uri : "/";

    if (uri == "/" || uri == "/index.html") {
        SendBytes(conn, "text/html; charset=utf-8", web_index_html_data, web_index_html_size);
        return 200;
    }
    if (uri == "/console.js") {
        SendBytes(conn, "text/javascript; charset=utf-8", web_console_js_data, web_console_js_size);
        return 200;
    }
    if (uri == "/console.css") {
        SendBytes(conn, "text/css; charset=utf-8", web_console_css_data, web_console_css_size);
        return 200;
    }
    if (uri == "/api/login") {
        return self->HandleLogin(conn);
    }
    mg_printf(conn, "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n");
    return 404;
}

int ConsoleServer::HandleLogin(mg_connection* conn) {
    const mg_request_info* ri = mg_get_request_info(conn);
    std::string addr = ri->remote_addr;  // civetweb fills a fixed char[]; always valid
    auto now = clock_t_::now();

    if (!impl_->OriginAllowed(mg_get_header(conn, "Origin"))) {
        mg_printf(conn, "HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\n\r\n");
        return 403;
    }
    {
        std::lock_guard<std::mutex> lk(impl_->rl_mutex);
        auto& r = impl_->rate[addr];
        if (r.lockout_until > now) {
            mg_printf(conn, "HTTP/1.1 429 Too Many Requests\r\nContent-Length: 0\r\n\r\n");
            return 429;
        }
    }

    char buf[2048];
    int n = mg_read(conn, buf, sizeof(buf) - 1);
    if (n < 0) n = 0;
    buf[n] = 0;
    json body = json::parse(buf, nullptr, false);
    std::string password = (!body.is_discarded() && body.contains("password")) ? body["password"].get<std::string>() : "";

    if (!password.empty() && VerifyPassword(password, config_.password_hash)) {
        {
            std::lock_guard<std::mutex> lk(impl_->rl_mutex);
            impl_->rate[addr].fails = 0;
        }
        std::string token = RandomToken();
        {
            std::lock_guard<std::mutex> lk(impl_->sess_mutex);
            impl_->sessions[token] = {now, now, addr};
        }
        std::string out = json{{"ok", true}, {"token", token}}.dump();
        mg_printf(conn,
                  "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
                  "Set-Cookie: vox_session=%s; HttpOnly; Secure; SameSite=Strict; Path=/\r\n"
                  "Content-Length: %zu\r\n\r\n%s",
                  token.c_str(), out.size(), out.c_str());
        vox::log::Info("console: session opened from {}", addr);
        return 200;
    }

    // failed auth -> backoff
    int fails;
    {
        std::lock_guard<std::mutex> lk(impl_->rl_mutex);
        auto& r = impl_->rate[addr];
        fails = ++r.fails;
        if (fails >= config_.fails_for_lockout) {
            int over = fails - config_.fails_for_lockout;
            int secs = config_.lockout_seconds * (1 << (over > 5 ? 5 : over));
            r.lockout_until = now + std::chrono::seconds(secs);
            vox::log::Warn("console: {} locked out for {}s after {} failed attempts", addr, secs, fails);
        }
    }
    if (impl_->total_fails.fetch_add(1) + 1 >= 20) {
        vox::log::Error("console: 20 failed auths -> unbinding ConsoleServer (restart required)");
        impl_->force_unbind = true;
    }
    std::string out = json{{"ok", false}, {"error", "invalid password"}}.dump();
    mg_printf(conn, "HTTP/1.1 401 Unauthorized\r\nContent-Type: application/json\r\nContent-Length: %zu\r\n\r\n%s",
              out.size(), out.c_str());
    return 401;
}

// ---- WebSocket ------------------------------------------------------------
int ConsoleServer::WsConnect(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    const mg_request_info* ri = mg_get_request_info(conn);

    if (!self->impl_->OriginAllowed(mg_get_header(conn, "Origin"))) {
        return 403;  // reject before any auth check
    }
    std::string cookieTok = CookieValue(mg_get_header(conn, "Cookie"), "vox_session");
    std::string queryTok = QueryParam(ri->query_string, "token");
    // Cookie + matching query-param token (defeats cross-tab CSRF), both valid.
    if (cookieTok.empty() || cookieTok != queryTok || !self->impl_->SessionValid(cookieTok)) {
        return 401;
    }
    return 0;  // accept
}

void ConsoleServer::WsReady(mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    std::lock_guard<std::mutex> lk(self->impl_->ws_mutex);
    self->impl_->ws_clients[conn];  // default-construct empty topic set
}

int ConsoleServer::WsData(mg_connection* conn, int bits, char* data, std::size_t len, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    if ((bits & 0xF) == MG_WEBSOCKET_OPCODE_TEXT && len > 0) {
        // Handle on the main thread so all registry access is single-threaded.
        self->console_->QueueTask(
            [self, conn, s = std::string(data, len)]() { self->HandleMessage(conn, s); });
    }
    return 1;  // keep open
}

void ConsoleServer::WsClose(const mg_connection* conn, void* cbdata) {
    auto* self = static_cast<ConsoleServer*>(cbdata);
    std::lock_guard<std::mutex> lk(self->impl_->ws_mutex);
    self->impl_->ws_clients.erase(conn);
}

void ConsoleServer::SendWs(const mg_connection* conn, const std::string& text) {
    std::lock_guard<std::mutex> lk(impl_->ws_mutex);
    if (impl_->ws_clients.find(conn) == impl_->ws_clients.end()) return;  // closed
    mg_websocket_write(const_cast<mg_connection*>(conn), MG_WEBSOCKET_OPCODE_TEXT, text.data(), text.size());
}

// Runs on the main thread (via Console::Drain).
void ConsoleServer::HandleMessage(const mg_connection* conn, const std::string& text) {
    json msg = json::parse(text, nullptr, false);
    if (msg.is_discarded()) return;
    std::string type = msg.value("type", "");
    std::string id = msg.value("id", "");
    auto reply = [&](json r) {
        r["type"] = "result";
        if (!id.empty()) r["id"] = id;
        SendWs(conn, r.dump());
    };

    if (type == "list_cvars") {
        json arr = json::array();
        console_->EnumerateCVars("", [&](CVar& cv) { arr.push_back(CvarToJson(cv)); });
        reply({{"ok", true}, {"cvars", arr}});
    } else if (type == "list_commands") {
        json arr = json::array();
        console_->EnumerateCommands("", [&](Command& c) { arr.push_back(json{{"name", c.name}, {"description", c.description}}); });
        reply({{"ok", true}, {"commands", arr}});
    } else if (type == "get_cvar") {
        CVar* cv = console_->FindCVar(msg.value("name", ""));
        if (cv) reply({{"ok", true}, {"cvar", CvarToJson(*cv)}});
        else reply({{"ok", false}, {"error", "unknown cvar"}});
    } else if (type == "set_cvar") {
        std::string name = msg.value("name", "");
        std::string value = msg.value("value", "");
        ExecuteResult r = console_->Execute(name + " " + value);
        json out{{"ok", r.ok}};
        if (!r.error.empty()) out["error"] = r.error;
        if (CVar* cv = console_->FindCVar(name)) out["cvar"] = CvarToJson(*cv);
        reply(out);
    } else if (type == "exec") {
        ExecuteResult r = console_->Execute(msg.value("line", ""));
        json out{{"ok", r.ok}};
        if (!r.output.empty()) out["output"] = r.output;
        if (!r.error.empty()) out["error"] = r.error;
        reply(out);
    } else if (type == "subscribe" || type == "unsubscribe") {
        std::lock_guard<std::mutex> lk(impl_->ws_mutex);
        auto it = impl_->ws_clients.find(conn);
        if (it != impl_->ws_clients.end() && msg.contains("topics")) {
            for (auto& t : msg["topics"]) {
                if (type == "subscribe") it->second.insert(t.get<std::string>());
                else it->second.erase(t.get<std::string>());
            }
        }
    } else {
        reply({{"ok", false}, {"error", "unknown message type: " + type}});
    }
}

// ---- TCP line protocol ----------------------------------------------------
void ConsoleServer::StartLineServer() {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        vox::log::Warn("console: WSAStartup failed; TCP automation disabled");
        return;
    }
    impl_->wsa_started = true;
    SOCKET s = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (s == INVALID_SOCKET) {
        vox::log::Warn("console: line socket() failed");
        return;
    }
    BOOL yes = TRUE;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<const char*>(&yes), sizeof(yes));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(config_.line_port);
    InetPtonA(AF_INET, config_.bind_address.c_str(), &addr.sin_addr);
    if (::bind(s, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) == SOCKET_ERROR || ::listen(s, 4) == SOCKET_ERROR) {
        vox::log::Warn("console: line bind/listen on {}:{} failed", config_.bind_address, config_.line_port);
        closesocket(s);
        return;
    }
    impl_->line_sock = s;
    impl_->line_run = true;
    impl_->line_thread = std::thread([this] { LineAcceptLoop(); });
    vox::log::Info("console: TCP automation listening on {}:{} (password on first line)", config_.bind_address,
                   config_.line_port);
}

void ConsoleServer::LineAcceptLoop() {
    while (impl_->line_run.load()) {
        SOCKET c = ::accept(impl_->line_sock, nullptr, nullptr);
        if (c == INVALID_SOCKET) {
            if (!impl_->line_run.load()) break;
            continue;
        }
        DWORD tmo = 1000;  // 1s recv timeout so workers notice shutdown
        setsockopt(c, SOL_SOCKET, SO_RCVTIMEO, reinterpret_cast<const char*>(&tmo), sizeof(tmo));
        impl_->line_workers.emplace_back([this, c] { LineClientLoop(static_cast<std::uintptr_t>(c)); });
    }
}

void ConsoleServer::LineClientLoop(std::uintptr_t client) {
    SOCKET sock = static_cast<SOCKET>(client);
    std::string buf;
    auto readLine = [&](std::string& out) -> bool {
        for (;;) {
            auto nl = buf.find('\n');
            if (nl != std::string::npos) {
                out = buf.substr(0, nl);
                if (!out.empty() && out.back() == '\r') out.pop_back();
                buf.erase(0, nl + 1);
                return true;
            }
            char tmp[512];
            int n = ::recv(sock, tmp, sizeof(tmp), 0);
            if (n > 0) {
                buf.append(tmp, n);
                continue;
            }
            if (n == 0) return false;  // peer closed
            if (!impl_->line_run.load()) return false;
            if (WSAGetLastError() == WSAETIMEDOUT) continue;
            return false;
        }
    };
    auto sendStr = [&](const std::string& s) { ::send(sock, s.data(), static_cast<int>(s.size()), 0); };

    std::string pw;
    if (!readLine(pw) || !VerifyPassword(pw, config_.password_hash)) {
        sendStr("error: authentication failed\n");
        closesocket(sock);
        return;
    }
    sendStr("ok: authenticated\n");

    std::string line;
    while (impl_->line_run.load() && readLine(line)) {
        if (line.empty()) continue;
        if (line == "quit" || line == "exit") break;
        auto prom = std::make_shared<std::promise<std::string>>();
        auto fut = prom->get_future();
        console_->QueueTask([this, line, prom] {
            ExecuteResult r = console_->Execute(line);
            prom->set_value(r.ok ? (r.output.empty() ? "ok\n" : r.output + "\n") : ("error: " + r.error + "\n"));
        });
        if (fut.wait_for(std::chrono::seconds(2)) == std::future_status::ready) sendStr(fut.get());
        else sendStr("error: timeout\n");
    }
    closesocket(sock);
}

// ---- lifecycle ------------------------------------------------------------
ConsoleServer::ConsoleServer() : impl_(std::make_unique<Impl>()) {}
ConsoleServer::~ConsoleServer() { Stop(); }

bool ConsoleServer::Start(const Config& cfg, Console* console) {
    config_ = cfg;
    console_ = console;

    if (config_.password_hash.empty()) {
        vox::log::Error("ConsoleServer not bound: remote.password_hash unset.");
        vox::log::Error("  Set one and restart:  voxhammer --remote-password=<password>");
        return false;
    }
    if (sodium_init() < 0) {
        vox::log::Error("ConsoleServer: libsodium init failed");
        return false;
    }

    impl_->ttl_seconds = config_.session_ttl_seconds;
    impl_->port = config_.http_port;

    std::string portSpec = fmt::format("{}:{}", config_.bind_address, config_.http_port);

#if defined(VOX_HAVE_TLS)
    if (config_.enable_tls) {
        std::filesystem::create_directories(config_.cert_dir);
        impl_->cert_path = (std::filesystem::path(config_.cert_dir) / "cert.pem").string();
        if (!std::filesystem::exists(impl_->cert_path)) {
            impl_->fingerprint = GenerateSelfSignedCert(impl_->cert_path);
            if (impl_->fingerprint.empty()) {
                vox::log::Error("ConsoleServer: failed to generate TLS cert at {}", impl_->cert_path);
                return false;
            }
            vox::log::Info("console: generated self-signed cert at {}", impl_->cert_path);
        } else {
            // Load existing to recompute fingerprint for the log (memory BIO,
            // no FILE* -> OpenSSL on Windows).
            std::ifstream in(impl_->cert_path, std::ios::binary);
            std::string pem((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
            if (BIO* bio = BIO_new_mem_buf(pem.data(), static_cast<int>(pem.size()))) {
                X509* x = PEM_read_bio_X509(bio, nullptr, nullptr, nullptr);
                if (x) { impl_->fingerprint = Sha256Fingerprint(x); X509_free(x); }
                BIO_free(bio);
            }
        }
        impl_->tls = true;
        portSpec += "s";  // civetweb: 's' suffix = SSL
        vox::log::Info("console: TLS cert SHA-256 = {}", impl_->fingerprint);
        vox::log::Info("  (verify this fingerprint in your browser on first connect)");
    }
#endif

    const char* opts[] = {
        "listening_ports", portSpec.c_str(),
        "num_threads", "6",
        "enable_keep_alive", "yes",
        "websocket_timeout_ms", "3600000",
#if defined(VOX_HAVE_TLS)
        "ssl_certificate", impl_->tls ? impl_->cert_path.c_str() : "",
        "ssl_protocol_version", "4",  // TLS 1.2+
#endif
        nullptr,
    };

    mg_callbacks cb;
    std::memset(&cb, 0, sizeof(cb));
    impl_->ctx = mg_start(&cb, this, opts);
    if (!impl_->ctx) {
        vox::log::Error("ConsoleServer: mg_start failed (port {} in use? cert invalid?)", config_.http_port);
        return false;
    }
    mg_set_request_handler(impl_->ctx, "/", &HttpHandler, this);
    mg_set_request_handler(impl_->ctx, "/console.js", &HttpHandler, this);
    mg_set_request_handler(impl_->ctx, "/console.css", &HttpHandler, this);
    mg_set_request_handler(impl_->ctx, "/api/login", &HttpHandler, this);
    mg_set_websocket_handler(impl_->ctx, "/ws", &WsConnect, &WsReady, &WsData, &WsClose, this);

    vox::log::SetSink([this](vox::log::Level lvl, const std::string& body) {
        BroadcastEvent("log", json{{"level", vox::log::LevelName(lvl)}, {"message", body}}.dump());
    });

    running_ = true;
    StartLineServer();
    vox::log::Info("console: serving {}://{}:{}/", impl_->tls ? "https" : "http", config_.bind_address,
                   config_.http_port);
    return true;
}

void ConsoleServer::Stop() {
    if (!running_) return;
    vox::log::SetSink({});
    if (impl_->ctx) {
        mg_stop(impl_->ctx);
        impl_->ctx = nullptr;
    }
    // Tear down the TCP line server.
    impl_->line_run = false;
    if (impl_->line_sock != INVALID_SOCKET) {
        closesocket(impl_->line_sock);
        impl_->line_sock = INVALID_SOCKET;
    }
    if (impl_->line_thread.joinable()) impl_->line_thread.join();
    for (auto& w : impl_->line_workers) {
        if (w.joinable()) w.join();
    }
    impl_->line_workers.clear();
    if (impl_->wsa_started) {
        WSACleanup();
        impl_->wsa_started = false;
    }
    running_ = false;
}

bool ConsoleServer::UnbindRequested() const { return impl_->force_unbind.load(); }

void ConsoleServer::BroadcastEvent(std::string_view topic, std::string_view data_json) {
    if (!running_) return;
    double ts = std::chrono::duration<double>(clock_t_::now().time_since_epoch()).count();
    std::string env = fmt::format(R"({{"type":"event","topic":"{}","ts":{},"data":{}}})", topic, ts, data_json);
    std::lock_guard<std::mutex> lk(impl_->ws_mutex);
    for (auto& [conn, topics] : impl_->ws_clients) {
        if (topics.count(std::string(topic))) {
            mg_websocket_write(const_cast<mg_connection*>(conn), MG_WEBSOCKET_OPCODE_TEXT, env.data(), env.size());
        }
    }
}

void ConsoleServer::RotateCert() {
#if defined(VOX_HAVE_TLS)
    if (impl_->cert_path.empty()) return;
    std::error_code ec;
    std::filesystem::remove(impl_->cert_path, ec);
    impl_->fingerprint = GenerateSelfSignedCert(impl_->cert_path);
    vox::log::Warn("console.rotate_cert: new SHA-256 = {} (takes effect on restart; reconnect + re-verify)",
                   impl_->fingerprint);
#endif
}

void ConsoleServer::RotateSessions() {
    std::lock_guard<std::mutex> lk(impl_->sess_mutex);
    std::size_t n = impl_->sessions.size();
    impl_->sessions.clear();
    vox::log::Info("console.rotate_sessions: invalidated {} sessions", n);
}

std::string ConsoleServer::ListSessions() const {
    std::lock_guard<std::mutex> lk(impl_->sess_mutex);
    auto now = clock_t_::now();
    std::string out = fmt::format("{} active session(s):\n", impl_->sessions.size());
    for (auto& [tok, s] : impl_->sessions) {
        out += fmt::format("  {}… source={} age={}s idle={}s\n", tok.substr(0, 8), s.source,
                           std::chrono::duration_cast<std::chrono::seconds>(now - s.created).count(),
                           std::chrono::duration_cast<std::chrono::seconds>(now - s.last_active).count());
    }
    return out;
}

}  // namespace vox::console

#else  // ---- console server disabled (stub) ----

namespace vox::console {
struct ConsoleServer::Impl {};
ConsoleServer::ConsoleServer() : impl_(std::make_unique<Impl>()) {}
ConsoleServer::~ConsoleServer() {}
bool ConsoleServer::Start(const Config& cfg, Console* console) {
    config_ = cfg;
    console_ = console;
    if (config_.password_hash.empty()) {
        vox::log::Error("ConsoleServer not bound: remote.password_hash unset.");
        vox::log::Error("  Set one and restart:  voxhammer --remote-password=<password>");
        return false;
    }
    vox::log::Warn("ConsoleServer: built without the 'console' feature; not binding.");
    (void)web_index_html_size;
    return false;
}
void ConsoleServer::Stop() { running_ = false; }
bool ConsoleServer::UnbindRequested() const { return false; }
void ConsoleServer::BroadcastEvent(std::string_view, std::string_view) {}
void ConsoleServer::RotateCert() {}
void ConsoleServer::RotateSessions() {}
std::string ConsoleServer::ListSessions() const { return {}; }
}  // namespace vox::console

#endif
