// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Rajesh D'Monte
#include "ispc/IspcKernels.h"

#if defined(VOX_ENABLE_ISPC)
#include "saxpy_ispc.h"  // generated by vox_target_ispc (cmake/VoxIspc.cmake)
#endif

namespace vox::ispc {

void Saxpy(float a, const float* x, const float* y, float* out, int n) {
#if defined(VOX_ENABLE_ISPC)
    ::ispc::saxpy(a, const_cast<float*>(x), const_cast<float*>(y), out, n);
#else
    for (int i = 0; i < n; ++i) {
        out[i] = a * x[i] + y[i];
    }
#endif
}

}  // namespace vox::ispc
